### ISSUE TITLE
Validation errors and warnings related to SVG files

### ISSUE THREAD

**Issue by jmooring** [KKKZOZ/hugo-admonitions#3]
Create a page with this Markdown:

<details>
<summary>example.md</summary>

```text
> [!ABSTRACT]
> This is an abstract.

> [!CAUTION]
> This is a caution.

> [!CODE]
> This is code.

> [!CONCLUSION]
> This is a conclusion.

> [!DANGER]
> This is a danger.

> [!ERROR]
> This is an error.

> [!EXAMPLE]
> This is an example.

> [!EXPERIMENT]
> This is an experiment.

> [!GOAL]
> This is a goal.

> [!IDEA]
> This is an idea.

> [!IMPORTANT]
> This is important.

> [!INFO]
> This is information.

> [!MEMO]
> This is a memo.

> [!NOTE]
> This is a note.

> [!NOTIFY]
> This is a notification.

> [!QUESTION]
> This is a question.

> [!QUOTE]
> This is a quote.

> [!SUCCESS]
> This is a success.

> [!TASK]
> This is a task.

> [!TIP]
> This is a tip.

> [!WARNING]
> This is a warning.
```
</details>

Then build the site and validate the published HTML file:
<https://validator.w3.org/#validate_by_input>

There are 40 errors and warnings such as:

![image](https://github.com/user-attachments/assets/faa5527d-fb61-4da6-891a-efac5cd1d059)

**Comment by KKKZOZ** [comment]
I'll look into these SVG validation issues and fix them as soon as possible

**Comment by jmooring** [comment]
I think import/export though Illustrator should clean these up. Let me know if you want to me to give it a try.

**Comment by KKKZOZ** [comment]
> I think import/export though Illustrator should clean these up. Let me know if you want to me to give it a try.

Yes, Thanks. That would be very helpful!
