### ISSUE TITLE
proposal: Update README

### ISSUE THREAD

**Issue by jmooring** [KKKZOZ/hugo-admonitions#7]
Nothing urgent.

1. Explain how to localize/override using i18n files, and indicate that localization PRs are welcome.
2. Explain how to override color scheme by copying `assets/css/admonitions/style.scss` to the root of the project and changing as needed.
3. Update examples

Regarding license/attribution for the free set of Font Awesome icons... no action required:

> Attribution is required by MIT, SIL OFL, and CC BY licenses. Downloaded Font Awesome Free files already contain embedded comments with sufficient attribution, **so you shouldn't need to do anything additional when using these files normally**.
>
> https://fontawesome.com/license/free#attribution

**Comment by KKKZOZ** [comment]
Good advice!

I'll push the changes by the end of this Tuesday then close this issue. 🚀
