### ISSUE TITLE
proposal: use 'admonitions' instead of 'notice' to namespace CSS classes

### ISSUE THREAD

**Issue by jmooring** [KKKZOZ/hugo-admonitions#8]
This is a bit of a nit, but we've namespaced the partials and i18n keys using the word "admonitions", which matches the name of this module. Perhaps we can do the  same with the CSS classes?

**Comment by KKKZOZ** [comment]
Good advice, this will make the code more consistent!

I'll push the changes soon then close this issue.🚀
